use bankingdb;
select firstName, upper(firstname) as Upper_Case from customers;
select firstname, lower(firstname) as lower_case from customers;
select firstname, length(firstname) as length_name from customers;
select firstname, left(firstname, 3) as starting_3 from customers;
select firstname, right(firstname, 3) as ending_3 from customers;
select concat(firstname, " - ", lastname) as full_name from customers;
select round(3434.23) as rounded;
select round(3434.73) as rounded;
select ceil(1256.23) as ceiling_value;
select floor(1256.98) as floor_value;
select abs(-3456) as absolute;
select mod(567,3) as remainder;
select curdate();
select now();
select dateofbirth, year(dateofbirth) as birth_year from customers;
select dateofbirth, month(dateofbirth) as month_year from customers;
select customerid, dateofbirth, datediff(curdate(), dateofbirth) as days from customers;
select firstname, dateofbirth, if(year(dateofbirth) <= 1995, "Adult","Young") as Age_category from customers;
select * from customers;
insert into customers(customerid, firstname, lastname,email, accountcreationdate, dateofbirth)  values(107, "Ganesh", "Tayade","gt@gmail.com","2026-04-23","2000-1-7");
delete from customers where customerid = 107;
select firstname, ifnull(phone, "Not Available") as phonenumber from customers;
select greatest("2002-04-9","2001-4-5","2007-5-12","1999-3-12","2004-04-19") as Latest_date;
select least("2002-04-9","2001-4-5","2007-5-12","1999-3-12","2004-04-19") as Latest_date;
select firstname, nullif(firstname, "Priya") as result from customers;
select sum(balance) as total_balance from accounts;
select avg(balance) as average_balance from accounts;
select max(balance) as maximum_balance from accounts;
select * from accounts where balance = (select max(balance) from accounts);
select min(balance) as lowest_balance from accounts;
select count(*) as total_accounts from accounts;
select sum(balance) from accounts;
select accounttype, sum(balance) as type_balance from accounts group by AccountType;
select accounttype, sum(balance) as type_balance from accounts group by AccountType having sum(balance) > 50000;